// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: vm_host_registry.proto

package virtualmachinegrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Host struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HostId           string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AgentId          string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ZoneId           string                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneSlug         string                 `protobuf:"bytes,4,opt,name=zone_slug,json=zoneSlug,proto3" json:"zone_slug,omitempty"`
	DataPlaneId      string                 `protobuf:"bytes,5,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PrivateIp        string                 `protobuf:"bytes,7,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	HypervisorType   string                 `protobuf:"bytes,8,opt,name=hypervisor_type,json=hypervisorType,proto3" json:"hypervisor_type,omitempty"`
	AgentVersion     string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CapabilitiesJson string                 `protobuf:"bytes,10,opt,name=capabilities_json,json=capabilitiesJson,proto3" json:"capabilities_json,omitempty"`
	CpuCores         int32                  `protobuf:"varint,11,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes      int64                  `protobuf:"varint,12,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes        int64                  `protobuf:"varint,13,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	Status           string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_vm_host_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_vm_host_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_vm_host_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Host) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Host) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Host) GetZoneSlug() string {
	if x != nil {
		return x.ZoneSlug
	}
	return ""
}

func (x *Host) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Host) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *Host) GetHypervisorType() string {
	if x != nil {
		return x.HypervisorType
	}
	return ""
}

func (x *Host) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Host) GetCapabilitiesJson() string {
	if x != nil {
		return x.CapabilitiesJson
	}
	return ""
}

func (x *Host) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Host) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Host) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *Host) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Host) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *Host) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Host) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpsertHostRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId      string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	HostId           string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AgentId          string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ZoneSlug         string                 `protobuf:"bytes,4,opt,name=zone_slug,json=zoneSlug,proto3" json:"zone_slug,omitempty"`
	Hostname         string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PrivateIp        string                 `protobuf:"bytes,6,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	HypervisorType   string                 `protobuf:"bytes,7,opt,name=hypervisor_type,json=hypervisorType,proto3" json:"hypervisor_type,omitempty"`
	AgentVersion     string                 `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CapabilitiesJson string                 `protobuf:"bytes,9,opt,name=capabilities_json,json=capabilitiesJson,proto3" json:"capabilities_json,omitempty"`
	CpuCores         int32                  `protobuf:"varint,10,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes      int64                  `protobuf:"varint,11,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes        int64                  `protobuf:"varint,12,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	Status           string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpsertHostRequest) Reset() {
	*x = UpsertHostRequest{}
	mi := &file_vm_host_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertHostRequest) ProtoMessage() {}

func (x *UpsertHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vm_host_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertHostRequest.ProtoReflect.Descriptor instead.
func (*UpsertHostRequest) Descriptor() ([]byte, []int) {
	return file_vm_host_registry_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertHostRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *UpsertHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *UpsertHostRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpsertHostRequest) GetZoneSlug() string {
	if x != nil {
		return x.ZoneSlug
	}
	return ""
}

func (x *UpsertHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *UpsertHostRequest) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *UpsertHostRequest) GetHypervisorType() string {
	if x != nil {
		return x.HypervisorType
	}
	return ""
}

func (x *UpsertHostRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *UpsertHostRequest) GetCapabilitiesJson() string {
	if x != nil {
		return x.CapabilitiesJson
	}
	return ""
}

func (x *UpsertHostRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *UpsertHostRequest) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *UpsertHostRequest) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *UpsertHostRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpsertHostRequest) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type UpsertHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *Host                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertHostResponse) Reset() {
	*x = UpsertHostResponse{}
	mi := &file_vm_host_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertHostResponse) ProtoMessage() {}

func (x *UpsertHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vm_host_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertHostResponse.ProtoReflect.Descriptor instead.
func (*UpsertHostResponse) Descriptor() ([]byte, []int) {
	return file_vm_host_registry_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertHostResponse) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

type UpdateHostStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId   string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostStatusRequest) Reset() {
	*x = UpdateHostStatusRequest{}
	mi := &file_vm_host_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostStatusRequest) ProtoMessage() {}

func (x *UpdateHostStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vm_host_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateHostStatusRequest) Descriptor() ([]byte, []int) {
	return file_vm_host_registry_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateHostStatusRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *UpdateHostStatusRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *UpdateHostStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateHostStatusRequest) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type UpdateHostStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *Host                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostStatusResponse) Reset() {
	*x = UpdateHostStatusResponse{}
	mi := &file_vm_host_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostStatusResponse) ProtoMessage() {}

func (x *UpdateHostStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vm_host_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateHostStatusResponse) Descriptor() ([]byte, []int) {
	return file_vm_host_registry_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateHostStatusResponse) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

type GetHostBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostBindingRequest) Reset() {
	*x = GetHostBindingRequest{}
	mi := &file_vm_host_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostBindingRequest) ProtoMessage() {}

func (x *GetHostBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vm_host_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostBindingRequest.ProtoReflect.Descriptor instead.
func (*GetHostBindingRequest) Descriptor() ([]byte, []int) {
	return file_vm_host_registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetHostBindingRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *GetHostBindingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetHostBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Host          *Host                  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostBindingResponse) Reset() {
	*x = GetHostBindingResponse{}
	mi := &file_vm_host_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostBindingResponse) ProtoMessage() {}

func (x *GetHostBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vm_host_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostBindingResponse.ProtoReflect.Descriptor instead.
func (*GetHostBindingResponse) Descriptor() ([]byte, []int) {
	return file_vm_host_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetHostBindingResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *GetHostBindingResponse) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

var File_vm_host_registry_proto protoreflect.FileDescriptor

const file_vm_host_registry_proto_rawDesc = "" +
	"\n" +
	"\x16vm_host_registry.proto\x12\x1avirtualmachine.registry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x04\n" +
	"\x04Host\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\tzone_slug\x18\x04 \x01(\tR\bzoneSlug\x12\"\n" +
	"\rdata_plane_id\x18\x05 \x01(\tR\vdataPlaneId\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"private_ip\x18\a \x01(\tR\tprivateIp\x12'\n" +
	"\x0fhypervisor_type\x18\b \x01(\tR\x0ehypervisorType\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\x12+\n" +
	"\x11capabilities_json\x18\n" +
	" \x01(\tR\x10capabilitiesJson\x12\x1b\n" +
	"\tcpu_cores\x18\v \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\f \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\r \x01(\x03R\tdiskBytes\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12<\n" +
	"\flast_seen_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf3\x03\n" +
	"\x11UpsertHostRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1b\n" +
	"\tzone_slug\x18\x04 \x01(\tR\bzoneSlug\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x06 \x01(\tR\tprivateIp\x12'\n" +
	"\x0fhypervisor_type\x18\a \x01(\tR\x0ehypervisorType\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x12+\n" +
	"\x11capabilities_json\x18\t \x01(\tR\x10capabilitiesJson\x12\x1b\n" +
	"\tcpu_cores\x18\n" +
	" \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\v \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\f \x01(\x03R\tdiskBytes\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12<\n" +
	"\flast_seen_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"J\n" +
	"\x12UpsertHostResponse\x124\n" +
	"\x04host\x18\x01 \x01(\v2 .virtualmachine.registry.v1.HostR\x04host\"\xac\x01\n" +
	"\x17UpdateHostStatusRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12<\n" +
	"\flast_seen_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"P\n" +
	"\x18UpdateHostStatusResponse\x124\n" +
	"\x04host\x18\x01 \x01(\v2 .virtualmachine.registry.v1.HostR\x04host\"K\n" +
	"\x15GetHostBindingRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"h\n" +
	"\x16GetHostBindingResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x124\n" +
	"\x04host\x18\x02 \x01(\v2 .virtualmachine.registry.v1.HostR\x04host2\xfd\x02\n" +
	"\x16VirtualMachineRegistry\x12k\n" +
	"\n" +
	"UpsertHost\x12-.virtualmachine.registry.v1.UpsertHostRequest\x1a..virtualmachine.registry.v1.UpsertHostResponse\x12}\n" +
	"\x10UpdateHostStatus\x123.virtualmachine.registry.v1.UpdateHostStatusRequest\x1a4.virtualmachine.registry.v1.UpdateHostStatusResponse\x12w\n" +
	"\x0eGetHostBinding\x121.virtualmachine.registry.v1.GetHostBindingRequest\x1a2.virtualmachine.registry.v1.GetHostBindingResponseBHZFcontrolplane/internal/virtualmachine/transport/grpc;virtualmachinegrpcb\x06proto3"

var (
	file_vm_host_registry_proto_rawDescOnce sync.Once
	file_vm_host_registry_proto_rawDescData []byte
)

func file_vm_host_registry_proto_rawDescGZIP() []byte {
	file_vm_host_registry_proto_rawDescOnce.Do(func() {
		file_vm_host_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vm_host_registry_proto_rawDesc), len(file_vm_host_registry_proto_rawDesc)))
	})
	return file_vm_host_registry_proto_rawDescData
}

var file_vm_host_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vm_host_registry_proto_goTypes = []any{
	(*Host)(nil),                     // 0: virtualmachine.registry.v1.Host
	(*UpsertHostRequest)(nil),        // 1: virtualmachine.registry.v1.UpsertHostRequest
	(*UpsertHostResponse)(nil),       // 2: virtualmachine.registry.v1.UpsertHostResponse
	(*UpdateHostStatusRequest)(nil),  // 3: virtualmachine.registry.v1.UpdateHostStatusRequest
	(*UpdateHostStatusResponse)(nil), // 4: virtualmachine.registry.v1.UpdateHostStatusResponse
	(*GetHostBindingRequest)(nil),    // 5: virtualmachine.registry.v1.GetHostBindingRequest
	(*GetHostBindingResponse)(nil),   // 6: virtualmachine.registry.v1.GetHostBindingResponse
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_vm_host_registry_proto_depIdxs = []int32{
	7,  // 0: virtualmachine.registry.v1.Host.last_seen_at:type_name -> google.protobuf.Timestamp
	7,  // 1: virtualmachine.registry.v1.Host.created_at:type_name -> google.protobuf.Timestamp
	7,  // 2: virtualmachine.registry.v1.Host.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 3: virtualmachine.registry.v1.UpsertHostRequest.last_seen_at:type_name -> google.protobuf.Timestamp
	0,  // 4: virtualmachine.registry.v1.UpsertHostResponse.host:type_name -> virtualmachine.registry.v1.Host
	7,  // 5: virtualmachine.registry.v1.UpdateHostStatusRequest.last_seen_at:type_name -> google.protobuf.Timestamp
	0,  // 6: virtualmachine.registry.v1.UpdateHostStatusResponse.host:type_name -> virtualmachine.registry.v1.Host
	0,  // 7: virtualmachine.registry.v1.GetHostBindingResponse.host:type_name -> virtualmachine.registry.v1.Host
	1,  // 8: virtualmachine.registry.v1.VirtualMachineRegistry.UpsertHost:input_type -> virtualmachine.registry.v1.UpsertHostRequest
	3,  // 9: virtualmachine.registry.v1.VirtualMachineRegistry.UpdateHostStatus:input_type -> virtualmachine.registry.v1.UpdateHostStatusRequest
	5,  // 10: virtualmachine.registry.v1.VirtualMachineRegistry.GetHostBinding:input_type -> virtualmachine.registry.v1.GetHostBindingRequest
	2,  // 11: virtualmachine.registry.v1.VirtualMachineRegistry.UpsertHost:output_type -> virtualmachine.registry.v1.UpsertHostResponse
	4,  // 12: virtualmachine.registry.v1.VirtualMachineRegistry.UpdateHostStatus:output_type -> virtualmachine.registry.v1.UpdateHostStatusResponse
	6,  // 13: virtualmachine.registry.v1.VirtualMachineRegistry.GetHostBinding:output_type -> virtualmachine.registry.v1.GetHostBindingResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_vm_host_registry_proto_init() }
func file_vm_host_registry_proto_init() {
	if File_vm_host_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vm_host_registry_proto_rawDesc), len(file_vm_host_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vm_host_registry_proto_goTypes,
		DependencyIndexes: file_vm_host_registry_proto_depIdxs,
		MessageInfos:      file_vm_host_registry_proto_msgTypes,
	}.Build()
	File_vm_host_registry_proto = out.File
	file_vm_host_registry_proto_goTypes = nil
	file_vm_host_registry_proto_depIdxs = nil
}
