// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: vm_host_registry.proto

package virtualmachinegrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VirtualMachineRegistry_UpsertHost_FullMethodName       = "/virtualmachine.registry.v1.VirtualMachineRegistry/UpsertHost"
	VirtualMachineRegistry_UpdateHostStatus_FullMethodName = "/virtualmachine.registry.v1.VirtualMachineRegistry/UpdateHostStatus"
	VirtualMachineRegistry_GetHostBinding_FullMethodName   = "/virtualmachine.registry.v1.VirtualMachineRegistry/GetHostBinding"
)

// VirtualMachineRegistryClient is the client API for VirtualMachineRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirtualMachineRegistryClient interface {
	UpsertHost(ctx context.Context, in *UpsertHostRequest, opts ...grpc.CallOption) (*UpsertHostResponse, error)
	UpdateHostStatus(ctx context.Context, in *UpdateHostStatusRequest, opts ...grpc.CallOption) (*UpdateHostStatusResponse, error)
	GetHostBinding(ctx context.Context, in *GetHostBindingRequest, opts ...grpc.CallOption) (*GetHostBindingResponse, error)
}

type virtualMachineRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualMachineRegistryClient(cc grpc.ClientConnInterface) VirtualMachineRegistryClient {
	return &virtualMachineRegistryClient{cc}
}

func (c *virtualMachineRegistryClient) UpsertHost(ctx context.Context, in *UpsertHostRequest, opts ...grpc.CallOption) (*UpsertHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertHostResponse)
	err := c.cc.Invoke(ctx, VirtualMachineRegistry_UpsertHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineRegistryClient) UpdateHostStatus(ctx context.Context, in *UpdateHostStatusRequest, opts ...grpc.CallOption) (*UpdateHostStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHostStatusResponse)
	err := c.cc.Invoke(ctx, VirtualMachineRegistry_UpdateHostStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineRegistryClient) GetHostBinding(ctx context.Context, in *GetHostBindingRequest, opts ...grpc.CallOption) (*GetHostBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostBindingResponse)
	err := c.cc.Invoke(ctx, VirtualMachineRegistry_GetHostBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineRegistryServer is the server API for VirtualMachineRegistry service.
// All implementations should embed UnimplementedVirtualMachineRegistryServer
// for forward compatibility.
type VirtualMachineRegistryServer interface {
	UpsertHost(context.Context, *UpsertHostRequest) (*UpsertHostResponse, error)
	UpdateHostStatus(context.Context, *UpdateHostStatusRequest) (*UpdateHostStatusResponse, error)
	GetHostBinding(context.Context, *GetHostBindingRequest) (*GetHostBindingResponse, error)
}

// UnimplementedVirtualMachineRegistryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVirtualMachineRegistryServer struct{}

func (UnimplementedVirtualMachineRegistryServer) UpsertHost(context.Context, *UpsertHostRequest) (*UpsertHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertHost not implemented")
}
func (UnimplementedVirtualMachineRegistryServer) UpdateHostStatus(context.Context, *UpdateHostStatusRequest) (*UpdateHostStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostStatus not implemented")
}
func (UnimplementedVirtualMachineRegistryServer) GetHostBinding(context.Context, *GetHostBindingRequest) (*GetHostBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostBinding not implemented")
}
func (UnimplementedVirtualMachineRegistryServer) testEmbeddedByValue() {}

// UnsafeVirtualMachineRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtualMachineRegistryServer will
// result in compilation errors.
type UnsafeVirtualMachineRegistryServer interface {
	mustEmbedUnimplementedVirtualMachineRegistryServer()
}

func RegisterVirtualMachineRegistryServer(s grpc.ServiceRegistrar, srv VirtualMachineRegistryServer) {
	// If the following call pancis, it indicates UnimplementedVirtualMachineRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VirtualMachineRegistry_ServiceDesc, srv)
}

func _VirtualMachineRegistry_UpsertHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineRegistryServer).UpsertHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualMachineRegistry_UpsertHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineRegistryServer).UpsertHost(ctx, req.(*UpsertHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineRegistry_UpdateHostStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineRegistryServer).UpdateHostStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualMachineRegistry_UpdateHostStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineRegistryServer).UpdateHostStatus(ctx, req.(*UpdateHostStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineRegistry_GetHostBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineRegistryServer).GetHostBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualMachineRegistry_GetHostBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineRegistryServer).GetHostBinding(ctx, req.(*GetHostBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VirtualMachineRegistry_ServiceDesc is the grpc.ServiceDesc for VirtualMachineRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtualMachineRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "virtualmachine.registry.v1.VirtualMachineRegistry",
	HandlerType: (*VirtualMachineRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertHost",
			Handler:    _VirtualMachineRegistry_UpsertHost_Handler,
		},
		{
			MethodName: "UpdateHostStatus",
			Handler:    _VirtualMachineRegistry_UpdateHostStatus_Handler,
		},
		{
			MethodName: "GetHostBinding",
			Handler:    _VirtualMachineRegistry_GetHostBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm_host_registry.proto",
}
