// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: controlplane_registry.proto

package controlplanegrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataPlaneRegistry_EnrollDataPlane_FullMethodName    = "/controlplane.registry.v1.DataPlaneRegistry/EnrollDataPlane"
	DataPlaneRegistry_HeartbeatDataPlane_FullMethodName = "/controlplane.registry.v1.DataPlaneRegistry/HeartbeatDataPlane"
)

// DataPlaneRegistryClient is the client API for DataPlaneRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataPlaneRegistryClient interface {
	EnrollDataPlane(ctx context.Context, in *EnrollDataPlaneRequest, opts ...grpc.CallOption) (*EnrollDataPlaneResponse, error)
	HeartbeatDataPlane(ctx context.Context, in *HeartbeatDataPlaneRequest, opts ...grpc.CallOption) (*HeartbeatDataPlaneResponse, error)
}

type dataPlaneRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneRegistryClient(cc grpc.ClientConnInterface) DataPlaneRegistryClient {
	return &dataPlaneRegistryClient{cc}
}

func (c *dataPlaneRegistryClient) EnrollDataPlane(ctx context.Context, in *EnrollDataPlaneRequest, opts ...grpc.CallOption) (*EnrollDataPlaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollDataPlaneResponse)
	err := c.cc.Invoke(ctx, DataPlaneRegistry_EnrollDataPlane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneRegistryClient) HeartbeatDataPlane(ctx context.Context, in *HeartbeatDataPlaneRequest, opts ...grpc.CallOption) (*HeartbeatDataPlaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatDataPlaneResponse)
	err := c.cc.Invoke(ctx, DataPlaneRegistry_HeartbeatDataPlane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataPlaneRegistryServer is the server API for DataPlaneRegistry service.
// All implementations should embed UnimplementedDataPlaneRegistryServer
// for forward compatibility.
type DataPlaneRegistryServer interface {
	EnrollDataPlane(context.Context, *EnrollDataPlaneRequest) (*EnrollDataPlaneResponse, error)
	HeartbeatDataPlane(context.Context, *HeartbeatDataPlaneRequest) (*HeartbeatDataPlaneResponse, error)
}

// UnimplementedDataPlaneRegistryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataPlaneRegistryServer struct{}

func (UnimplementedDataPlaneRegistryServer) EnrollDataPlane(context.Context, *EnrollDataPlaneRequest) (*EnrollDataPlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollDataPlane not implemented")
}
func (UnimplementedDataPlaneRegistryServer) HeartbeatDataPlane(context.Context, *HeartbeatDataPlaneRequest) (*HeartbeatDataPlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatDataPlane not implemented")
}
func (UnimplementedDataPlaneRegistryServer) testEmbeddedByValue() {}

// UnsafeDataPlaneRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneRegistryServer will
// result in compilation errors.
type UnsafeDataPlaneRegistryServer interface {
	mustEmbedUnimplementedDataPlaneRegistryServer()
}

func RegisterDataPlaneRegistryServer(s grpc.ServiceRegistrar, srv DataPlaneRegistryServer) {
	// If the following call pancis, it indicates UnimplementedDataPlaneRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataPlaneRegistry_ServiceDesc, srv)
}

func _DataPlaneRegistry_EnrollDataPlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollDataPlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneRegistryServer).EnrollDataPlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneRegistry_EnrollDataPlane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneRegistryServer).EnrollDataPlane(ctx, req.(*EnrollDataPlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlaneRegistry_HeartbeatDataPlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatDataPlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneRegistryServer).HeartbeatDataPlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneRegistry_HeartbeatDataPlane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneRegistryServer).HeartbeatDataPlane(ctx, req.(*HeartbeatDataPlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataPlaneRegistry_ServiceDesc is the grpc.ServiceDesc for DataPlaneRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPlaneRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.registry.v1.DataPlaneRegistry",
	HandlerType: (*DataPlaneRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrollDataPlane",
			Handler:    _DataPlaneRegistry_EnrollDataPlane_Handler,
		},
		{
			MethodName: "HeartbeatDataPlane",
			Handler:    _DataPlaneRegistry_HeartbeatDataPlane_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane_registry.proto",
}
