// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: controlplane_registry.proto

package controlplanegrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollDataPlaneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BootstrapToken string                 `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	NodeKey        string                 `protobuf:"bytes,2,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ZoneSlug       string                 `protobuf:"bytes,4,opt,name=zone_slug,json=zoneSlug,proto3" json:"zone_slug,omitempty"`
	GrpcEndpoint   string                 `protobuf:"bytes,5,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	Version        string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	CsrPem         string                 `protobuf:"bytes,7,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrollDataPlaneRequest) Reset() {
	*x = EnrollDataPlaneRequest{}
	mi := &file_controlplane_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollDataPlaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDataPlaneRequest) ProtoMessage() {}

func (x *EnrollDataPlaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDataPlaneRequest.ProtoReflect.Descriptor instead.
func (*EnrollDataPlaneRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_registry_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollDataPlaneRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *EnrollDataPlaneRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *EnrollDataPlaneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrollDataPlaneRequest) GetZoneSlug() string {
	if x != nil {
		return x.ZoneSlug
	}
	return ""
}

func (x *EnrollDataPlaneRequest) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *EnrollDataPlaneRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnrollDataPlaneRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

type EnrollDataPlaneResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId              string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	ClientCertPem            string                 `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	CaCertPem                string                 `protobuf:"bytes,3,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	CertNotAfter             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cert_not_after,json=certNotAfter,proto3" json:"cert_not_after,omitempty"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,5,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EnrollDataPlaneResponse) Reset() {
	*x = EnrollDataPlaneResponse{}
	mi := &file_controlplane_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollDataPlaneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollDataPlaneResponse) ProtoMessage() {}

func (x *EnrollDataPlaneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollDataPlaneResponse.ProtoReflect.Descriptor instead.
func (*EnrollDataPlaneResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_registry_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollDataPlaneResponse) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *EnrollDataPlaneResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *EnrollDataPlaneResponse) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

func (x *EnrollDataPlaneResponse) GetCertNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CertNotAfter
	}
	return nil
}

func (x *EnrollDataPlaneResponse) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type HeartbeatDataPlaneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId   string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	GrpcEndpoint  string                 `protobuf:"bytes,2,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatDataPlaneRequest) Reset() {
	*x = HeartbeatDataPlaneRequest{}
	mi := &file_controlplane_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatDataPlaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatDataPlaneRequest) ProtoMessage() {}

func (x *HeartbeatDataPlaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatDataPlaneRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatDataPlaneRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_registry_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatDataPlaneRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *HeartbeatDataPlaneRequest) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *HeartbeatDataPlaneRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HeartbeatDataPlaneResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HeartbeatDataPlaneResponse) Reset() {
	*x = HeartbeatDataPlaneResponse{}
	mi := &file_controlplane_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatDataPlaneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatDataPlaneResponse) ProtoMessage() {}

func (x *HeartbeatDataPlaneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatDataPlaneResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatDataPlaneResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatDataPlaneResponse) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

var File_controlplane_registry_proto protoreflect.FileDescriptor

const file_controlplane_registry_proto_rawDesc = "" +
	"\n" +
	"\x1bcontrolplane_registry.proto\x12\x18controlplane.registry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x01\n" +
	"\x16EnrollDataPlaneRequest\x12'\n" +
	"\x0fbootstrap_token\x18\x01 \x01(\tR\x0ebootstrapToken\x12\x19\n" +
	"\bnode_key\x18\x02 \x01(\tR\anodeKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tzone_slug\x18\x04 \x01(\tR\bzoneSlug\x12#\n" +
	"\rgrpc_endpoint\x18\x05 \x01(\tR\fgrpcEndpoint\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x17\n" +
	"\acsr_pem\x18\a \x01(\tR\x06csrPem\"\x85\x02\n" +
	"\x17EnrollDataPlaneResponse\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\tR\rclientCertPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x03 \x01(\tR\tcaCertPem\x12@\n" +
	"\x0ecert_not_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fcertNotAfter\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x05 \x01(\rR\x18heartbeatIntervalSeconds\"~\n" +
	"\x19HeartbeatDataPlaneRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12#\n" +
	"\rgrpc_endpoint\x18\x02 \x01(\tR\fgrpcEndpoint\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"Z\n" +
	"\x1aHeartbeatDataPlaneResponse\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\rR\x18heartbeatIntervalSeconds2\x8c\x02\n" +
	"\x11DataPlaneRegistry\x12v\n" +
	"\x0fEnrollDataPlane\x120.controlplane.registry.v1.EnrollDataPlaneRequest\x1a1.controlplane.registry.v1.EnrollDataPlaneResponse\x12\x7f\n" +
	"\x12HeartbeatDataPlane\x123.controlplane.registry.v1.HeartbeatDataPlaneRequest\x1a4.controlplane.registry.v1.HeartbeatDataPlaneResponseBAZ?dataplane/internal/controlplane/transport/grpc;controlplanegrpcb\x06proto3"

var (
	file_controlplane_registry_proto_rawDescOnce sync.Once
	file_controlplane_registry_proto_rawDescData []byte
)

func file_controlplane_registry_proto_rawDescGZIP() []byte {
	file_controlplane_registry_proto_rawDescOnce.Do(func() {
		file_controlplane_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_registry_proto_rawDesc), len(file_controlplane_registry_proto_rawDesc)))
	})
	return file_controlplane_registry_proto_rawDescData
}

var file_controlplane_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_controlplane_registry_proto_goTypes = []any{
	(*EnrollDataPlaneRequest)(nil),     // 0: controlplane.registry.v1.EnrollDataPlaneRequest
	(*EnrollDataPlaneResponse)(nil),    // 1: controlplane.registry.v1.EnrollDataPlaneResponse
	(*HeartbeatDataPlaneRequest)(nil),  // 2: controlplane.registry.v1.HeartbeatDataPlaneRequest
	(*HeartbeatDataPlaneResponse)(nil), // 3: controlplane.registry.v1.HeartbeatDataPlaneResponse
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_controlplane_registry_proto_depIdxs = []int32{
	4, // 0: controlplane.registry.v1.EnrollDataPlaneResponse.cert_not_after:type_name -> google.protobuf.Timestamp
	0, // 1: controlplane.registry.v1.DataPlaneRegistry.EnrollDataPlane:input_type -> controlplane.registry.v1.EnrollDataPlaneRequest
	2, // 2: controlplane.registry.v1.DataPlaneRegistry.HeartbeatDataPlane:input_type -> controlplane.registry.v1.HeartbeatDataPlaneRequest
	1, // 3: controlplane.registry.v1.DataPlaneRegistry.EnrollDataPlane:output_type -> controlplane.registry.v1.EnrollDataPlaneResponse
	3, // 4: controlplane.registry.v1.DataPlaneRegistry.HeartbeatDataPlane:output_type -> controlplane.registry.v1.HeartbeatDataPlaneResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_controlplane_registry_proto_init() }
func file_controlplane_registry_proto_init() {
	if File_controlplane_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_registry_proto_rawDesc), len(file_controlplane_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_registry_proto_goTypes,
		DependencyIndexes: file_controlplane_registry_proto_depIdxs,
		MessageInfos:      file_controlplane_registry_proto_msgTypes,
	}.Build()
	File_controlplane_registry_proto = out.File
	file_controlplane_registry_proto_goTypes = nil
	file_controlplane_registry_proto_depIdxs = nil
}
