// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: smtp_runtime.proto

package smtpgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncSMTPRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId   string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	LocalVersion  int64                  `protobuf:"varint,2,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	GrpcEndpoint  string                 `protobuf:"bytes,4,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSMTPRuntimeRequest) Reset() {
	*x = SyncSMTPRuntimeRequest{}
	mi := &file_smtp_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSMTPRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSMTPRuntimeRequest) ProtoMessage() {}

func (x *SyncSMTPRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSMTPRuntimeRequest.ProtoReflect.Descriptor instead.
func (*SyncSMTPRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *SyncSMTPRuntimeRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *SyncSMTPRuntimeRequest) GetLocalVersion() int64 {
	if x != nil {
		return x.LocalVersion
	}
	return 0
}

func (x *SyncSMTPRuntimeRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *SyncSMTPRuntimeRequest) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

type SyncSMTPRuntimeResponse struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	RuntimeVersion      int64                      `protobuf:"varint,1,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	Consumers           []*ConsumerResource        `protobuf:"bytes,2,rep,name=consumers,proto3" json:"consumers,omitempty"`
	Templates           []*TemplateResource        `protobuf:"bytes,3,rep,name=templates,proto3" json:"templates,omitempty"`
	Gateways            []*GatewayResource         `protobuf:"bytes,4,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Endpoints           []*EndpointResource        `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	ConsumerAssignments []*ConsumerShardAssignment `protobuf:"bytes,6,rep,name=consumer_assignments,json=consumerAssignments,proto3" json:"consumer_assignments,omitempty"`
	GatewayAssignments  []*GatewayShardAssignment  `protobuf:"bytes,7,rep,name=gateway_assignments,json=gatewayAssignments,proto3" json:"gateway_assignments,omitempty"`
	SyncIntervalSeconds uint32                     `protobuf:"varint,8,opt,name=sync_interval_seconds,json=syncIntervalSeconds,proto3" json:"sync_interval_seconds,omitempty"`
	FullResync          bool                       `protobuf:"varint,9,opt,name=full_resync,json=fullResync,proto3" json:"full_resync,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SyncSMTPRuntimeResponse) Reset() {
	*x = SyncSMTPRuntimeResponse{}
	mi := &file_smtp_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSMTPRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSMTPRuntimeResponse) ProtoMessage() {}

func (x *SyncSMTPRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSMTPRuntimeResponse.ProtoReflect.Descriptor instead.
func (*SyncSMTPRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *SyncSMTPRuntimeResponse) GetRuntimeVersion() int64 {
	if x != nil {
		return x.RuntimeVersion
	}
	return 0
}

func (x *SyncSMTPRuntimeResponse) GetConsumers() []*ConsumerResource {
	if x != nil {
		return x.Consumers
	}
	return nil
}

func (x *SyncSMTPRuntimeResponse) GetTemplates() []*TemplateResource {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *SyncSMTPRuntimeResponse) GetGateways() []*GatewayResource {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *SyncSMTPRuntimeResponse) GetEndpoints() []*EndpointResource {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *SyncSMTPRuntimeResponse) GetConsumerAssignments() []*ConsumerShardAssignment {
	if x != nil {
		return x.ConsumerAssignments
	}
	return nil
}

func (x *SyncSMTPRuntimeResponse) GetGatewayAssignments() []*GatewayShardAssignment {
	if x != nil {
		return x.GatewayAssignments
	}
	return nil
}

func (x *SyncSMTPRuntimeResponse) GetSyncIntervalSeconds() uint32 {
	if x != nil {
		return x.SyncIntervalSeconds
	}
	return 0
}

func (x *SyncSMTPRuntimeResponse) GetFullResync() bool {
	if x != nil {
		return x.FullResync
	}
	return false
}

type ReportSMTPRuntimeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId      string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	LocalVersion     int64                  `protobuf:"varint,2,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	Capacity         int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	GrpcEndpoint     string                 `protobuf:"bytes,4,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	ConsumerStatuses []*ConsumerShardStatus `protobuf:"bytes,5,rep,name=consumer_statuses,json=consumerStatuses,proto3" json:"consumer_statuses,omitempty"`
	GatewayStatuses  []*GatewayShardStatus  `protobuf:"bytes,6,rep,name=gateway_statuses,json=gatewayStatuses,proto3" json:"gateway_statuses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportSMTPRuntimeRequest) Reset() {
	*x = ReportSMTPRuntimeRequest{}
	mi := &file_smtp_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSMTPRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSMTPRuntimeRequest) ProtoMessage() {}

func (x *ReportSMTPRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSMTPRuntimeRequest.ProtoReflect.Descriptor instead.
func (*ReportSMTPRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *ReportSMTPRuntimeRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *ReportSMTPRuntimeRequest) GetLocalVersion() int64 {
	if x != nil {
		return x.LocalVersion
	}
	return 0
}

func (x *ReportSMTPRuntimeRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ReportSMTPRuntimeRequest) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *ReportSMTPRuntimeRequest) GetConsumerStatuses() []*ConsumerShardStatus {
	if x != nil {
		return x.ConsumerStatuses
	}
	return nil
}

func (x *ReportSMTPRuntimeRequest) GetGatewayStatuses() []*GatewayShardStatus {
	if x != nil {
		return x.GatewayStatuses
	}
	return nil
}

type ReportSMTPRuntimeResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReportIntervalSeconds uint32                 `protobuf:"varint,1,opt,name=report_interval_seconds,json=reportIntervalSeconds,proto3" json:"report_interval_seconds,omitempty"`
	ForceResync           bool                   `protobuf:"varint,2,opt,name=force_resync,json=forceResync,proto3" json:"force_resync,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReportSMTPRuntimeResponse) Reset() {
	*x = ReportSMTPRuntimeResponse{}
	mi := &file_smtp_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSMTPRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSMTPRuntimeResponse) ProtoMessage() {}

func (x *ReportSMTPRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSMTPRuntimeResponse.ProtoReflect.Descriptor instead.
func (*ReportSMTPRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *ReportSMTPRuntimeResponse) GetReportIntervalSeconds() uint32 {
	if x != nil {
		return x.ReportIntervalSeconds
	}
	return 0
}

func (x *ReportSMTPRuntimeResponse) GetForceResync() bool {
	if x != nil {
		return x.ForceResync
	}
	return false
}

type ConsumerResource struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId          string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ZoneId               string                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Name                 string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	TransportType        string                 `protobuf:"bytes,5,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"`
	Source               string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	ConsumerGroup        string                 `protobuf:"bytes,7,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	WorkerConcurrency    int32                  `protobuf:"varint,8,opt,name=worker_concurrency,json=workerConcurrency,proto3" json:"worker_concurrency,omitempty"`
	AckTimeoutSeconds    int32                  `protobuf:"varint,9,opt,name=ack_timeout_seconds,json=ackTimeoutSeconds,proto3" json:"ack_timeout_seconds,omitempty"`
	BatchSize            int32                  `protobuf:"varint,10,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Status               string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Note                 string                 `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	ConnectionConfigJson []byte                 `protobuf:"bytes,13,opt,name=connection_config_json,json=connectionConfigJson,proto3" json:"connection_config_json,omitempty"`
	SecretConfigJson     []byte                 `protobuf:"bytes,14,opt,name=secret_config_json,json=secretConfigJson,proto3" json:"secret_config_json,omitempty"`
	SecretRef            string                 `protobuf:"bytes,15,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"`
	SecretVersion        int64                  `protobuf:"varint,16,opt,name=secret_version,json=secretVersion,proto3" json:"secret_version,omitempty"`
	DesiredShardCount    int32                  `protobuf:"varint,17,opt,name=desired_shard_count,json=desiredShardCount,proto3" json:"desired_shard_count,omitempty"`
	RuntimeVersion       int64                  `protobuf:"varint,18,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConsumerResource) Reset() {
	*x = ConsumerResource{}
	mi := &file_smtp_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerResource) ProtoMessage() {}

func (x *ConsumerResource) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerResource.ProtoReflect.Descriptor instead.
func (*ConsumerResource) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumerResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumerResource) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ConsumerResource) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ConsumerResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsumerResource) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *ConsumerResource) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConsumerResource) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *ConsumerResource) GetWorkerConcurrency() int32 {
	if x != nil {
		return x.WorkerConcurrency
	}
	return 0
}

func (x *ConsumerResource) GetAckTimeoutSeconds() int32 {
	if x != nil {
		return x.AckTimeoutSeconds
	}
	return 0
}

func (x *ConsumerResource) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ConsumerResource) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConsumerResource) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ConsumerResource) GetConnectionConfigJson() []byte {
	if x != nil {
		return x.ConnectionConfigJson
	}
	return nil
}

func (x *ConsumerResource) GetSecretConfigJson() []byte {
	if x != nil {
		return x.SecretConfigJson
	}
	return nil
}

func (x *ConsumerResource) GetSecretRef() string {
	if x != nil {
		return x.SecretRef
	}
	return ""
}

func (x *ConsumerResource) GetSecretVersion() int64 {
	if x != nil {
		return x.SecretVersion
	}
	return 0
}

func (x *ConsumerResource) GetDesiredShardCount() int32 {
	if x != nil {
		return x.DesiredShardCount
	}
	return 0
}

func (x *ConsumerResource) GetRuntimeVersion() int64 {
	if x != nil {
		return x.RuntimeVersion
	}
	return 0
}

type TemplateResource struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId         string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category            string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	TrafficClass        string                 `protobuf:"bytes,5,opt,name=traffic_class,json=trafficClass,proto3" json:"traffic_class,omitempty"`
	Subject             string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	FromEmail           string                 `protobuf:"bytes,7,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	ToEmail             string                 `protobuf:"bytes,8,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	Status              string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Variables           []string               `protobuf:"bytes,10,rep,name=variables,proto3" json:"variables,omitempty"`
	ConsumerId          string                 `protobuf:"bytes,11,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ActiveVersion       int32                  `protobuf:"varint,12,opt,name=active_version,json=activeVersion,proto3" json:"active_version,omitempty"`
	RetryMaxAttempts    int32                  `protobuf:"varint,13,opt,name=retry_max_attempts,json=retryMaxAttempts,proto3" json:"retry_max_attempts,omitempty"`
	RetryBackoffSeconds int32                  `protobuf:"varint,14,opt,name=retry_backoff_seconds,json=retryBackoffSeconds,proto3" json:"retry_backoff_seconds,omitempty"`
	TextBody            string                 `protobuf:"bytes,15,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	HtmlBody            string                 `protobuf:"bytes,16,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	RuntimeVersion      int64                  `protobuf:"varint,17,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TemplateResource) Reset() {
	*x = TemplateResource{}
	mi := &file_smtp_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateResource) ProtoMessage() {}

func (x *TemplateResource) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateResource.ProtoReflect.Descriptor instead.
func (*TemplateResource) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *TemplateResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateResource) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *TemplateResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateResource) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TemplateResource) GetTrafficClass() string {
	if x != nil {
		return x.TrafficClass
	}
	return ""
}

func (x *TemplateResource) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TemplateResource) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *TemplateResource) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *TemplateResource) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TemplateResource) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *TemplateResource) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *TemplateResource) GetActiveVersion() int32 {
	if x != nil {
		return x.ActiveVersion
	}
	return 0
}

func (x *TemplateResource) GetRetryMaxAttempts() int32 {
	if x != nil {
		return x.RetryMaxAttempts
	}
	return 0
}

func (x *TemplateResource) GetRetryBackoffSeconds() int32 {
	if x != nil {
		return x.RetryBackoffSeconds
	}
	return 0
}

func (x *TemplateResource) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *TemplateResource) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *TemplateResource) GetRuntimeVersion() int64 {
	if x != nil {
		return x.RuntimeVersion
	}
	return 0
}

type GatewayResource struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId       string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ZoneId            string                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	TrafficClass      string                 `protobuf:"bytes,5,opt,name=traffic_class,json=trafficClass,proto3" json:"traffic_class,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RoutingMode       string                 `protobuf:"bytes,7,opt,name=routing_mode,json=routingMode,proto3" json:"routing_mode,omitempty"`
	Priority          int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	FallbackGatewayId string                 `protobuf:"bytes,9,opt,name=fallback_gateway_id,json=fallbackGatewayId,proto3" json:"fallback_gateway_id,omitempty"`
	DesiredShardCount int32                  `protobuf:"varint,10,opt,name=desired_shard_count,json=desiredShardCount,proto3" json:"desired_shard_count,omitempty"`
	TemplateIds       []string               `protobuf:"bytes,11,rep,name=template_ids,json=templateIds,proto3" json:"template_ids,omitempty"`
	EndpointIds       []string               `protobuf:"bytes,12,rep,name=endpoint_ids,json=endpointIds,proto3" json:"endpoint_ids,omitempty"`
	RuntimeVersion    int64                  `protobuf:"varint,13,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatewayResource) Reset() {
	*x = GatewayResource{}
	mi := &file_smtp_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayResource) ProtoMessage() {}

func (x *GatewayResource) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayResource.ProtoReflect.Descriptor instead.
func (*GatewayResource) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *GatewayResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GatewayResource) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GatewayResource) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *GatewayResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GatewayResource) GetTrafficClass() string {
	if x != nil {
		return x.TrafficClass
	}
	return ""
}

func (x *GatewayResource) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GatewayResource) GetRoutingMode() string {
	if x != nil {
		return x.RoutingMode
	}
	return ""
}

func (x *GatewayResource) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *GatewayResource) GetFallbackGatewayId() string {
	if x != nil {
		return x.FallbackGatewayId
	}
	return ""
}

func (x *GatewayResource) GetDesiredShardCount() int32 {
	if x != nil {
		return x.DesiredShardCount
	}
	return 0
}

func (x *GatewayResource) GetTemplateIds() []string {
	if x != nil {
		return x.TemplateIds
	}
	return nil
}

func (x *GatewayResource) GetEndpointIds() []string {
	if x != nil {
		return x.EndpointIds
	}
	return nil
}

func (x *GatewayResource) GetRuntimeVersion() int64 {
	if x != nil {
		return x.RuntimeVersion
	}
	return 0
}

type EndpointResource struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId          string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ProviderKind         string                 `protobuf:"bytes,4,opt,name=provider_kind,json=providerKind,proto3" json:"provider_kind,omitempty"`
	Host                 string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Username             string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Priority             int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight               int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	MaxConnections       int32                  `protobuf:"varint,10,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	MaxParallelSends     int32                  `protobuf:"varint,11,opt,name=max_parallel_sends,json=maxParallelSends,proto3" json:"max_parallel_sends,omitempty"`
	MaxMessagesPerSecond int32                  `protobuf:"varint,12,opt,name=max_messages_per_second,json=maxMessagesPerSecond,proto3" json:"max_messages_per_second,omitempty"`
	Burst                int32                  `protobuf:"varint,13,opt,name=burst,proto3" json:"burst,omitempty"`
	WarmupState          string                 `protobuf:"bytes,14,opt,name=warmup_state,json=warmupState,proto3" json:"warmup_state,omitempty"`
	Status               string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	TlsMode              string                 `protobuf:"bytes,16,opt,name=tls_mode,json=tlsMode,proto3" json:"tls_mode,omitempty"`
	Password             string                 `protobuf:"bytes,17,opt,name=password,proto3" json:"password,omitempty"`
	CaCertPem            string                 `protobuf:"bytes,18,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	ClientCertPem        string                 `protobuf:"bytes,19,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientKeyPem         string                 `protobuf:"bytes,20,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	SecretRef            string                 `protobuf:"bytes,21,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"`
	SecretVersion        int64                  `protobuf:"varint,22,opt,name=secret_version,json=secretVersion,proto3" json:"secret_version,omitempty"`
	RuntimeVersion       int64                  `protobuf:"varint,23,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EndpointResource) Reset() {
	*x = EndpointResource{}
	mi := &file_smtp_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointResource) ProtoMessage() {}

func (x *EndpointResource) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointResource.ProtoReflect.Descriptor instead.
func (*EndpointResource) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *EndpointResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndpointResource) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *EndpointResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointResource) GetProviderKind() string {
	if x != nil {
		return x.ProviderKind
	}
	return ""
}

func (x *EndpointResource) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EndpointResource) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EndpointResource) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EndpointResource) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EndpointResource) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *EndpointResource) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *EndpointResource) GetMaxParallelSends() int32 {
	if x != nil {
		return x.MaxParallelSends
	}
	return 0
}

func (x *EndpointResource) GetMaxMessagesPerSecond() int32 {
	if x != nil {
		return x.MaxMessagesPerSecond
	}
	return 0
}

func (x *EndpointResource) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *EndpointResource) GetWarmupState() string {
	if x != nil {
		return x.WarmupState
	}
	return ""
}

func (x *EndpointResource) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EndpointResource) GetTlsMode() string {
	if x != nil {
		return x.TlsMode
	}
	return ""
}

func (x *EndpointResource) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EndpointResource) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

func (x *EndpointResource) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *EndpointResource) GetClientKeyPem() string {
	if x != nil {
		return x.ClientKeyPem
	}
	return ""
}

func (x *EndpointResource) GetSecretRef() string {
	if x != nil {
		return x.SecretRef
	}
	return ""
}

func (x *EndpointResource) GetSecretVersion() int64 {
	if x != nil {
		return x.SecretVersion
	}
	return 0
}

func (x *EndpointResource) GetRuntimeVersion() int64 {
	if x != nil {
		return x.RuntimeVersion
	}
	return 0
}

type ConsumerShardAssignment struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId                string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ShardId                   int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	DataPlaneId               string                 `protobuf:"bytes,3,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	Generation                int64                  `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	AssignmentState           string                 `protobuf:"bytes,5,opt,name=assignment_state,json=assignmentState,proto3" json:"assignment_state,omitempty"`
	DesiredState              string                 `protobuf:"bytes,6,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	LeaseExpiresAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	TargetGatewayId           string                 `protobuf:"bytes,8,opt,name=target_gateway_id,json=targetGatewayId,proto3" json:"target_gateway_id,omitempty"`
	TargetGatewayShardId      int32                  `protobuf:"varint,9,opt,name=target_gateway_shard_id,json=targetGatewayShardId,proto3" json:"target_gateway_shard_id,omitempty"`
	TargetGatewayDataPlaneId  string                 `protobuf:"bytes,10,opt,name=target_gateway_data_plane_id,json=targetGatewayDataPlaneId,proto3" json:"target_gateway_data_plane_id,omitempty"`
	TargetGatewayGrpcEndpoint string                 `protobuf:"bytes,11,opt,name=target_gateway_grpc_endpoint,json=targetGatewayGrpcEndpoint,proto3" json:"target_gateway_grpc_endpoint,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ConsumerShardAssignment) Reset() {
	*x = ConsumerShardAssignment{}
	mi := &file_smtp_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerShardAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerShardAssignment) ProtoMessage() {}

func (x *ConsumerShardAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerShardAssignment.ProtoReflect.Descriptor instead.
func (*ConsumerShardAssignment) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *ConsumerShardAssignment) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumerShardAssignment) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ConsumerShardAssignment) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *ConsumerShardAssignment) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ConsumerShardAssignment) GetAssignmentState() string {
	if x != nil {
		return x.AssignmentState
	}
	return ""
}

func (x *ConsumerShardAssignment) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *ConsumerShardAssignment) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *ConsumerShardAssignment) GetTargetGatewayId() string {
	if x != nil {
		return x.TargetGatewayId
	}
	return ""
}

func (x *ConsumerShardAssignment) GetTargetGatewayShardId() int32 {
	if x != nil {
		return x.TargetGatewayShardId
	}
	return 0
}

func (x *ConsumerShardAssignment) GetTargetGatewayDataPlaneId() string {
	if x != nil {
		return x.TargetGatewayDataPlaneId
	}
	return ""
}

func (x *ConsumerShardAssignment) GetTargetGatewayGrpcEndpoint() string {
	if x != nil {
		return x.TargetGatewayGrpcEndpoint
	}
	return ""
}

type GatewayShardAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GatewayId       string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	ShardId         int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	DataPlaneId     string                 `protobuf:"bytes,3,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	Generation      int64                  `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	AssignmentState string                 `protobuf:"bytes,5,opt,name=assignment_state,json=assignmentState,proto3" json:"assignment_state,omitempty"`
	DesiredState    string                 `protobuf:"bytes,6,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	LeaseExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	GrpcEndpoint    string                 `protobuf:"bytes,8,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GatewayShardAssignment) Reset() {
	*x = GatewayShardAssignment{}
	mi := &file_smtp_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayShardAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayShardAssignment) ProtoMessage() {}

func (x *GatewayShardAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayShardAssignment.ProtoReflect.Descriptor instead.
func (*GatewayShardAssignment) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayShardAssignment) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayShardAssignment) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *GatewayShardAssignment) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *GatewayShardAssignment) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *GatewayShardAssignment) GetAssignmentState() string {
	if x != nil {
		return x.AssignmentState
	}
	return ""
}

func (x *GatewayShardAssignment) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *GatewayShardAssignment) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *GatewayShardAssignment) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

type ConsumerShardStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId         string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ShardId            int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	GatewayId          string                 `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	InflightCount      int64                  `protobuf:"varint,5,opt,name=inflight_count,json=inflightCount,proto3" json:"inflight_count,omitempty"`
	BrokerLag          int64                  `protobuf:"varint,6,opt,name=broker_lag,json=brokerLag,proto3" json:"broker_lag,omitempty"`
	OldestUnackedAgeMs int64                  `protobuf:"varint,7,opt,name=oldest_unacked_age_ms,json=oldestUnackedAgeMs,proto3" json:"oldest_unacked_age_ms,omitempty"`
	DesiredWorkers     int32                  `protobuf:"varint,8,opt,name=desired_workers,json=desiredWorkers,proto3" json:"desired_workers,omitempty"`
	ActiveWorkers      int32                  `protobuf:"varint,9,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	RelayQueueDepth    int64                  `protobuf:"varint,10,opt,name=relay_queue_depth,json=relayQueueDepth,proto3" json:"relay_queue_depth,omitempty"`
	LastError          string                 `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Generation         int64                  `protobuf:"varint,12,opt,name=generation,proto3" json:"generation,omitempty"`
	AssignmentState    string                 `protobuf:"bytes,13,opt,name=assignment_state,json=assignmentState,proto3" json:"assignment_state,omitempty"`
	RevokingDone       bool                   `protobuf:"varint,14,opt,name=revoking_done,json=revokingDone,proto3" json:"revoking_done,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsumerShardStatus) Reset() {
	*x = ConsumerShardStatus{}
	mi := &file_smtp_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerShardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerShardStatus) ProtoMessage() {}

func (x *ConsumerShardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerShardStatus.ProtoReflect.Descriptor instead.
func (*ConsumerShardStatus) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *ConsumerShardStatus) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumerShardStatus) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ConsumerShardStatus) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ConsumerShardStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConsumerShardStatus) GetInflightCount() int64 {
	if x != nil {
		return x.InflightCount
	}
	return 0
}

func (x *ConsumerShardStatus) GetBrokerLag() int64 {
	if x != nil {
		return x.BrokerLag
	}
	return 0
}

func (x *ConsumerShardStatus) GetOldestUnackedAgeMs() int64 {
	if x != nil {
		return x.OldestUnackedAgeMs
	}
	return 0
}

func (x *ConsumerShardStatus) GetDesiredWorkers() int32 {
	if x != nil {
		return x.DesiredWorkers
	}
	return 0
}

func (x *ConsumerShardStatus) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *ConsumerShardStatus) GetRelayQueueDepth() int64 {
	if x != nil {
		return x.RelayQueueDepth
	}
	return 0
}

func (x *ConsumerShardStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ConsumerShardStatus) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ConsumerShardStatus) GetAssignmentState() string {
	if x != nil {
		return x.AssignmentState
	}
	return ""
}

func (x *ConsumerShardStatus) GetRevokingDone() bool {
	if x != nil {
		return x.RevokingDone
	}
	return false
}

type GatewayShardStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GatewayId         string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	ShardId           int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	InflightCount     int64                  `protobuf:"varint,4,opt,name=inflight_count,json=inflightCount,proto3" json:"inflight_count,omitempty"`
	DesiredWorkers    int32                  `protobuf:"varint,5,opt,name=desired_workers,json=desiredWorkers,proto3" json:"desired_workers,omitempty"`
	ActiveWorkers     int32                  `protobuf:"varint,6,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	RelayQueueDepth   int64                  `protobuf:"varint,7,opt,name=relay_queue_depth,json=relayQueueDepth,proto3" json:"relay_queue_depth,omitempty"`
	PoolOpenConns     int32                  `protobuf:"varint,8,opt,name=pool_open_conns,json=poolOpenConns,proto3" json:"pool_open_conns,omitempty"`
	PoolBusyConns     int32                  `protobuf:"varint,9,opt,name=pool_busy_conns,json=poolBusyConns,proto3" json:"pool_busy_conns,omitempty"`
	SendRatePerSecond float64                `protobuf:"fixed64,10,opt,name=send_rate_per_second,json=sendRatePerSecond,proto3" json:"send_rate_per_second,omitempty"`
	BackpressureState string                 `protobuf:"bytes,11,opt,name=backpressure_state,json=backpressureState,proto3" json:"backpressure_state,omitempty"`
	LastError         string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Generation        int64                  `protobuf:"varint,13,opt,name=generation,proto3" json:"generation,omitempty"`
	AssignmentState   string                 `protobuf:"bytes,14,opt,name=assignment_state,json=assignmentState,proto3" json:"assignment_state,omitempty"`
	RevokingDone      bool                   `protobuf:"varint,15,opt,name=revoking_done,json=revokingDone,proto3" json:"revoking_done,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatewayShardStatus) Reset() {
	*x = GatewayShardStatus{}
	mi := &file_smtp_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayShardStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayShardStatus) ProtoMessage() {}

func (x *GatewayShardStatus) ProtoReflect() protoreflect.Message {
	mi := &file_smtp_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayShardStatus.ProtoReflect.Descriptor instead.
func (*GatewayShardStatus) Descriptor() ([]byte, []int) {
	return file_smtp_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *GatewayShardStatus) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayShardStatus) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *GatewayShardStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GatewayShardStatus) GetInflightCount() int64 {
	if x != nil {
		return x.InflightCount
	}
	return 0
}

func (x *GatewayShardStatus) GetDesiredWorkers() int32 {
	if x != nil {
		return x.DesiredWorkers
	}
	return 0
}

func (x *GatewayShardStatus) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *GatewayShardStatus) GetRelayQueueDepth() int64 {
	if x != nil {
		return x.RelayQueueDepth
	}
	return 0
}

func (x *GatewayShardStatus) GetPoolOpenConns() int32 {
	if x != nil {
		return x.PoolOpenConns
	}
	return 0
}

func (x *GatewayShardStatus) GetPoolBusyConns() int32 {
	if x != nil {
		return x.PoolBusyConns
	}
	return 0
}

func (x *GatewayShardStatus) GetSendRatePerSecond() float64 {
	if x != nil {
		return x.SendRatePerSecond
	}
	return 0
}

func (x *GatewayShardStatus) GetBackpressureState() string {
	if x != nil {
		return x.BackpressureState
	}
	return ""
}

func (x *GatewayShardStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *GatewayShardStatus) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *GatewayShardStatus) GetAssignmentState() string {
	if x != nil {
		return x.AssignmentState
	}
	return ""
}

func (x *GatewayShardStatus) GetRevokingDone() bool {
	if x != nil {
		return x.RevokingDone
	}
	return false
}

var File_smtp_runtime_proto protoreflect.FileDescriptor

const file_smtp_runtime_proto_rawDesc = "" +
	"\n" +
	"\x12smtp_runtime.proto\x12\x14controlplane.smtp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x16SyncSMTPRuntimeRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12#\n" +
	"\rlocal_version\x18\x02 \x01(\x03R\flocalVersion\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12#\n" +
	"\rgrpc_endpoint\x18\x04 \x01(\tR\fgrpcEndpoint\"\xed\x04\n" +
	"\x17SyncSMTPRuntimeResponse\x12'\n" +
	"\x0fruntime_version\x18\x01 \x01(\x03R\x0eruntimeVersion\x12D\n" +
	"\tconsumers\x18\x02 \x03(\v2&.controlplane.smtp.v1.ConsumerResourceR\tconsumers\x12D\n" +
	"\ttemplates\x18\x03 \x03(\v2&.controlplane.smtp.v1.TemplateResourceR\ttemplates\x12A\n" +
	"\bgateways\x18\x04 \x03(\v2%.controlplane.smtp.v1.GatewayResourceR\bgateways\x12D\n" +
	"\tendpoints\x18\x05 \x03(\v2&.controlplane.smtp.v1.EndpointResourceR\tendpoints\x12`\n" +
	"\x14consumer_assignments\x18\x06 \x03(\v2-.controlplane.smtp.v1.ConsumerShardAssignmentR\x13consumerAssignments\x12]\n" +
	"\x13gateway_assignments\x18\a \x03(\v2,.controlplane.smtp.v1.GatewayShardAssignmentR\x12gatewayAssignments\x122\n" +
	"\x15sync_interval_seconds\x18\b \x01(\rR\x13syncIntervalSeconds\x12\x1f\n" +
	"\vfull_resync\x18\t \x01(\bR\n" +
	"fullResync\"\xd1\x02\n" +
	"\x18ReportSMTPRuntimeRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12#\n" +
	"\rlocal_version\x18\x02 \x01(\x03R\flocalVersion\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12#\n" +
	"\rgrpc_endpoint\x18\x04 \x01(\tR\fgrpcEndpoint\x12V\n" +
	"\x11consumer_statuses\x18\x05 \x03(\v2).controlplane.smtp.v1.ConsumerShardStatusR\x10consumerStatuses\x12S\n" +
	"\x10gateway_statuses\x18\x06 \x03(\v2(.controlplane.smtp.v1.GatewayShardStatusR\x0fgatewayStatuses\"v\n" +
	"\x19ReportSMTPRuntimeResponse\x126\n" +
	"\x17report_interval_seconds\x18\x01 \x01(\rR\x15reportIntervalSeconds\x12!\n" +
	"\fforce_resync\x18\x02 \x01(\bR\vforceResync\"\x85\x05\n" +
	"\x10ConsumerResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x0etransport_type\x18\x05 \x01(\tR\rtransportType\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12%\n" +
	"\x0econsumer_group\x18\a \x01(\tR\rconsumerGroup\x12-\n" +
	"\x12worker_concurrency\x18\b \x01(\x05R\x11workerConcurrency\x12.\n" +
	"\x13ack_timeout_seconds\x18\t \x01(\x05R\x11ackTimeoutSeconds\x12\x1d\n" +
	"\n" +
	"batch_size\x18\n" +
	" \x01(\x05R\tbatchSize\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\f \x01(\tR\x04note\x124\n" +
	"\x16connection_config_json\x18\r \x01(\fR\x14connectionConfigJson\x12,\n" +
	"\x12secret_config_json\x18\x0e \x01(\fR\x10secretConfigJson\x12\x1d\n" +
	"\n" +
	"secret_ref\x18\x0f \x01(\tR\tsecretRef\x12%\n" +
	"\x0esecret_version\x18\x10 \x01(\x03R\rsecretVersion\x12.\n" +
	"\x13desired_shard_count\x18\x11 \x01(\x05R\x11desiredShardCount\x12'\n" +
	"\x0fruntime_version\x18\x12 \x01(\x03R\x0eruntimeVersion\"\xb1\x04\n" +
	"\x10TemplateResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12#\n" +
	"\rtraffic_class\x18\x05 \x01(\tR\ftrafficClass\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"from_email\x18\a \x01(\tR\tfromEmail\x12\x19\n" +
	"\bto_email\x18\b \x01(\tR\atoEmail\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1c\n" +
	"\tvariables\x18\n" +
	" \x03(\tR\tvariables\x12\x1f\n" +
	"\vconsumer_id\x18\v \x01(\tR\n" +
	"consumerId\x12%\n" +
	"\x0eactive_version\x18\f \x01(\x05R\ractiveVersion\x12,\n" +
	"\x12retry_max_attempts\x18\r \x01(\x05R\x10retryMaxAttempts\x122\n" +
	"\x15retry_backoff_seconds\x18\x0e \x01(\x05R\x13retryBackoffSeconds\x12\x1b\n" +
	"\ttext_body\x18\x0f \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\x10 \x01(\tR\bhtmlBody\x12'\n" +
	"\x0fruntime_version\x18\x11 \x01(\x03R\x0eruntimeVersion\"\xbc\x03\n" +
	"\x0fGatewayResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12#\n" +
	"\rtraffic_class\x18\x05 \x01(\tR\ftrafficClass\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12!\n" +
	"\frouting_mode\x18\a \x01(\tR\vroutingMode\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12.\n" +
	"\x13fallback_gateway_id\x18\t \x01(\tR\x11fallbackGatewayId\x12.\n" +
	"\x13desired_shard_count\x18\n" +
	" \x01(\x05R\x11desiredShardCount\x12!\n" +
	"\ftemplate_ids\x18\v \x03(\tR\vtemplateIds\x12!\n" +
	"\fendpoint_ids\x18\f \x03(\tR\vendpointIds\x12'\n" +
	"\x0fruntime_version\x18\r \x01(\x03R\x0eruntimeVersion\"\xe9\x05\n" +
	"\x10EndpointResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rprovider_kind\x18\x04 \x01(\tR\fproviderKind\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12'\n" +
	"\x0fmax_connections\x18\n" +
	" \x01(\x05R\x0emaxConnections\x12,\n" +
	"\x12max_parallel_sends\x18\v \x01(\x05R\x10maxParallelSends\x125\n" +
	"\x17max_messages_per_second\x18\f \x01(\x05R\x14maxMessagesPerSecond\x12\x14\n" +
	"\x05burst\x18\r \x01(\x05R\x05burst\x12!\n" +
	"\fwarmup_state\x18\x0e \x01(\tR\vwarmupState\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\x19\n" +
	"\btls_mode\x18\x10 \x01(\tR\atlsMode\x12\x1a\n" +
	"\bpassword\x18\x11 \x01(\tR\bpassword\x12\x1e\n" +
	"\vca_cert_pem\x18\x12 \x01(\tR\tcaCertPem\x12&\n" +
	"\x0fclient_cert_pem\x18\x13 \x01(\tR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x14 \x01(\tR\fclientKeyPem\x12\x1d\n" +
	"\n" +
	"secret_ref\x18\x15 \x01(\tR\tsecretRef\x12%\n" +
	"\x0esecret_version\x18\x16 \x01(\x03R\rsecretVersion\x12'\n" +
	"\x0fruntime_version\x18\x17 \x01(\x03R\x0eruntimeVersion\"\x93\x04\n" +
	"\x17ConsumerShardAssignment\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\"\n" +
	"\rdata_plane_id\x18\x03 \x01(\tR\vdataPlaneId\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x03R\n" +
	"generation\x12)\n" +
	"\x10assignment_state\x18\x05 \x01(\tR\x0fassignmentState\x12#\n" +
	"\rdesired_state\x18\x06 \x01(\tR\fdesiredState\x12D\n" +
	"\x10lease_expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12*\n" +
	"\x11target_gateway_id\x18\b \x01(\tR\x0ftargetGatewayId\x125\n" +
	"\x17target_gateway_shard_id\x18\t \x01(\x05R\x14targetGatewayShardId\x12>\n" +
	"\x1ctarget_gateway_data_plane_id\x18\n" +
	" \x01(\tR\x18targetGatewayDataPlaneId\x12?\n" +
	"\x1ctarget_gateway_grpc_endpoint\x18\v \x01(\tR\x19targetGatewayGrpcEndpoint\"\xd1\x02\n" +
	"\x16GatewayShardAssignment\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\"\n" +
	"\rdata_plane_id\x18\x03 \x01(\tR\vdataPlaneId\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x03R\n" +
	"generation\x12)\n" +
	"\x10assignment_state\x18\x05 \x01(\tR\x0fassignmentState\x12#\n" +
	"\rdesired_state\x18\x06 \x01(\tR\fdesiredState\x12D\n" +
	"\x10lease_expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12#\n" +
	"\rgrpc_endpoint\x18\b \x01(\tR\fgrpcEndpoint\"\x8c\x04\n" +
	"\x13ConsumerShardStatus\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0einflight_count\x18\x05 \x01(\x03R\rinflightCount\x12\x1d\n" +
	"\n" +
	"broker_lag\x18\x06 \x01(\x03R\tbrokerLag\x121\n" +
	"\x15oldest_unacked_age_ms\x18\a \x01(\x03R\x12oldestUnackedAgeMs\x12'\n" +
	"\x0fdesired_workers\x18\b \x01(\x05R\x0edesiredWorkers\x12%\n" +
	"\x0eactive_workers\x18\t \x01(\x05R\ractiveWorkers\x12*\n" +
	"\x11relay_queue_depth\x18\n" +
	" \x01(\x03R\x0frelayQueueDepth\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\x12\x1e\n" +
	"\n" +
	"generation\x18\f \x01(\x03R\n" +
	"generation\x12)\n" +
	"\x10assignment_state\x18\r \x01(\tR\x0fassignmentState\x12#\n" +
	"\rrevoking_done\x18\x0e \x01(\bR\frevokingDone\"\xc8\x04\n" +
	"\x12GatewayShardStatus\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0einflight_count\x18\x04 \x01(\x03R\rinflightCount\x12'\n" +
	"\x0fdesired_workers\x18\x05 \x01(\x05R\x0edesiredWorkers\x12%\n" +
	"\x0eactive_workers\x18\x06 \x01(\x05R\ractiveWorkers\x12*\n" +
	"\x11relay_queue_depth\x18\a \x01(\x03R\x0frelayQueueDepth\x12&\n" +
	"\x0fpool_open_conns\x18\b \x01(\x05R\rpoolOpenConns\x12&\n" +
	"\x0fpool_busy_conns\x18\t \x01(\x05R\rpoolBusyConns\x12/\n" +
	"\x14send_rate_per_second\x18\n" +
	" \x01(\x01R\x11sendRatePerSecond\x12-\n" +
	"\x12backpressure_state\x18\v \x01(\tR\x11backpressureState\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12\x1e\n" +
	"\n" +
	"generation\x18\r \x01(\x03R\n" +
	"generation\x12)\n" +
	"\x10assignment_state\x18\x0e \x01(\tR\x0fassignmentState\x12#\n" +
	"\rrevoking_done\x18\x0f \x01(\bR\frevokingDone2\xf3\x01\n" +
	"\vSMTPRuntime\x12n\n" +
	"\x0fSyncSMTPRuntime\x12,.controlplane.smtp.v1.SyncSMTPRuntimeRequest\x1a-.controlplane.smtp.v1.SyncSMTPRuntimeResponse\x12t\n" +
	"\x11ReportSMTPRuntime\x12..controlplane.smtp.v1.ReportSMTPRuntimeRequest\x1a/.controlplane.smtp.v1.ReportSMTPRuntimeResponseB1Z/dataplane/internal/smtp/transport/grpc;smtpgrpcb\x06proto3"

var (
	file_smtp_runtime_proto_rawDescOnce sync.Once
	file_smtp_runtime_proto_rawDescData []byte
)

func file_smtp_runtime_proto_rawDescGZIP() []byte {
	file_smtp_runtime_proto_rawDescOnce.Do(func() {
		file_smtp_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smtp_runtime_proto_rawDesc), len(file_smtp_runtime_proto_rawDesc)))
	})
	return file_smtp_runtime_proto_rawDescData
}

var file_smtp_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_smtp_runtime_proto_goTypes = []any{
	(*SyncSMTPRuntimeRequest)(nil),    // 0: controlplane.smtp.v1.SyncSMTPRuntimeRequest
	(*SyncSMTPRuntimeResponse)(nil),   // 1: controlplane.smtp.v1.SyncSMTPRuntimeResponse
	(*ReportSMTPRuntimeRequest)(nil),  // 2: controlplane.smtp.v1.ReportSMTPRuntimeRequest
	(*ReportSMTPRuntimeResponse)(nil), // 3: controlplane.smtp.v1.ReportSMTPRuntimeResponse
	(*ConsumerResource)(nil),          // 4: controlplane.smtp.v1.ConsumerResource
	(*TemplateResource)(nil),          // 5: controlplane.smtp.v1.TemplateResource
	(*GatewayResource)(nil),           // 6: controlplane.smtp.v1.GatewayResource
	(*EndpointResource)(nil),          // 7: controlplane.smtp.v1.EndpointResource
	(*ConsumerShardAssignment)(nil),   // 8: controlplane.smtp.v1.ConsumerShardAssignment
	(*GatewayShardAssignment)(nil),    // 9: controlplane.smtp.v1.GatewayShardAssignment
	(*ConsumerShardStatus)(nil),       // 10: controlplane.smtp.v1.ConsumerShardStatus
	(*GatewayShardStatus)(nil),        // 11: controlplane.smtp.v1.GatewayShardStatus
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_smtp_runtime_proto_depIdxs = []int32{
	4,  // 0: controlplane.smtp.v1.SyncSMTPRuntimeResponse.consumers:type_name -> controlplane.smtp.v1.ConsumerResource
	5,  // 1: controlplane.smtp.v1.SyncSMTPRuntimeResponse.templates:type_name -> controlplane.smtp.v1.TemplateResource
	6,  // 2: controlplane.smtp.v1.SyncSMTPRuntimeResponse.gateways:type_name -> controlplane.smtp.v1.GatewayResource
	7,  // 3: controlplane.smtp.v1.SyncSMTPRuntimeResponse.endpoints:type_name -> controlplane.smtp.v1.EndpointResource
	8,  // 4: controlplane.smtp.v1.SyncSMTPRuntimeResponse.consumer_assignments:type_name -> controlplane.smtp.v1.ConsumerShardAssignment
	9,  // 5: controlplane.smtp.v1.SyncSMTPRuntimeResponse.gateway_assignments:type_name -> controlplane.smtp.v1.GatewayShardAssignment
	10, // 6: controlplane.smtp.v1.ReportSMTPRuntimeRequest.consumer_statuses:type_name -> controlplane.smtp.v1.ConsumerShardStatus
	11, // 7: controlplane.smtp.v1.ReportSMTPRuntimeRequest.gateway_statuses:type_name -> controlplane.smtp.v1.GatewayShardStatus
	12, // 8: controlplane.smtp.v1.ConsumerShardAssignment.lease_expires_at:type_name -> google.protobuf.Timestamp
	12, // 9: controlplane.smtp.v1.GatewayShardAssignment.lease_expires_at:type_name -> google.protobuf.Timestamp
	0,  // 10: controlplane.smtp.v1.SMTPRuntime.SyncSMTPRuntime:input_type -> controlplane.smtp.v1.SyncSMTPRuntimeRequest
	2,  // 11: controlplane.smtp.v1.SMTPRuntime.ReportSMTPRuntime:input_type -> controlplane.smtp.v1.ReportSMTPRuntimeRequest
	1,  // 12: controlplane.smtp.v1.SMTPRuntime.SyncSMTPRuntime:output_type -> controlplane.smtp.v1.SyncSMTPRuntimeResponse
	3,  // 13: controlplane.smtp.v1.SMTPRuntime.ReportSMTPRuntime:output_type -> controlplane.smtp.v1.ReportSMTPRuntimeResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_smtp_runtime_proto_init() }
func file_smtp_runtime_proto_init() {
	if File_smtp_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smtp_runtime_proto_rawDesc), len(file_smtp_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smtp_runtime_proto_goTypes,
		DependencyIndexes: file_smtp_runtime_proto_depIdxs,
		MessageInfos:      file_smtp_runtime_proto_msgTypes,
	}.Build()
	File_smtp_runtime_proto = out.File
	file_smtp_runtime_proto_goTypes = nil
	file_smtp_runtime_proto_depIdxs = nil
}
