// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: smtp_runtime.proto

package smtpgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SMTPRuntime_SyncSMTPRuntime_FullMethodName   = "/controlplane.smtp.v1.SMTPRuntime/SyncSMTPRuntime"
	SMTPRuntime_ReportSMTPRuntime_FullMethodName = "/controlplane.smtp.v1.SMTPRuntime/ReportSMTPRuntime"
)

// SMTPRuntimeClient is the client API for SMTPRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SMTPRuntimeClient interface {
	SyncSMTPRuntime(ctx context.Context, in *SyncSMTPRuntimeRequest, opts ...grpc.CallOption) (*SyncSMTPRuntimeResponse, error)
	ReportSMTPRuntime(ctx context.Context, in *ReportSMTPRuntimeRequest, opts ...grpc.CallOption) (*ReportSMTPRuntimeResponse, error)
}

type sMTPRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewSMTPRuntimeClient(cc grpc.ClientConnInterface) SMTPRuntimeClient {
	return &sMTPRuntimeClient{cc}
}

func (c *sMTPRuntimeClient) SyncSMTPRuntime(ctx context.Context, in *SyncSMTPRuntimeRequest, opts ...grpc.CallOption) (*SyncSMTPRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncSMTPRuntimeResponse)
	err := c.cc.Invoke(ctx, SMTPRuntime_SyncSMTPRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMTPRuntimeClient) ReportSMTPRuntime(ctx context.Context, in *ReportSMTPRuntimeRequest, opts ...grpc.CallOption) (*ReportSMTPRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSMTPRuntimeResponse)
	err := c.cc.Invoke(ctx, SMTPRuntime_ReportSMTPRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMTPRuntimeServer is the server API for SMTPRuntime service.
// All implementations should embed UnimplementedSMTPRuntimeServer
// for forward compatibility.
type SMTPRuntimeServer interface {
	SyncSMTPRuntime(context.Context, *SyncSMTPRuntimeRequest) (*SyncSMTPRuntimeResponse, error)
	ReportSMTPRuntime(context.Context, *ReportSMTPRuntimeRequest) (*ReportSMTPRuntimeResponse, error)
}

// UnimplementedSMTPRuntimeServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSMTPRuntimeServer struct{}

func (UnimplementedSMTPRuntimeServer) SyncSMTPRuntime(context.Context, *SyncSMTPRuntimeRequest) (*SyncSMTPRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncSMTPRuntime not implemented")
}
func (UnimplementedSMTPRuntimeServer) ReportSMTPRuntime(context.Context, *ReportSMTPRuntimeRequest) (*ReportSMTPRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSMTPRuntime not implemented")
}
func (UnimplementedSMTPRuntimeServer) testEmbeddedByValue() {}

// UnsafeSMTPRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SMTPRuntimeServer will
// result in compilation errors.
type UnsafeSMTPRuntimeServer interface {
	mustEmbedUnimplementedSMTPRuntimeServer()
}

func RegisterSMTPRuntimeServer(s grpc.ServiceRegistrar, srv SMTPRuntimeServer) {
	// If the following call pancis, it indicates UnimplementedSMTPRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SMTPRuntime_ServiceDesc, srv)
}

func _SMTPRuntime_SyncSMTPRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSMTPRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMTPRuntimeServer).SyncSMTPRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMTPRuntime_SyncSMTPRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMTPRuntimeServer).SyncSMTPRuntime(ctx, req.(*SyncSMTPRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMTPRuntime_ReportSMTPRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSMTPRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMTPRuntimeServer).ReportSMTPRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMTPRuntime_ReportSMTPRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMTPRuntimeServer).ReportSMTPRuntime(ctx, req.(*ReportSMTPRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SMTPRuntime_ServiceDesc is the grpc.ServiceDesc for SMTPRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SMTPRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.smtp.v1.SMTPRuntime",
	HandlerType: (*SMTPRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncSMTPRuntime",
			Handler:    _SMTPRuntime_SyncSMTPRuntime_Handler,
		},
		{
			MethodName: "ReportSMTPRuntime",
			Handler:    _SMTPRuntime_ReportSMTPRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smtp_runtime.proto",
}
