import type {
  ConsumerItem,
  LaneRoute,
  DeliveryEndpoint,
  SMTPTab,
  TemplateItem,
} from "@/components/smtp/types";

export const tabs: SMTPTab[] = [
  {
    key: "general",
    label: "General",
    caption: "Analytics, health, throughput",
    href: "/smtp",
  },
  {
    key: "consumer",
    label: "Consumer",
    caption: "Redis stream and queue connectors",
    href: "/smtp/consumers",
  },
  {
    key: "template",
    label: "Template",
    caption: "Mail patterns and content library",
    href: "/smtp/templates",
  },
  {
    key: "lane",
    label: "Lane",
    caption: "Route traffic classes into delivery endpoints",
    href: "/smtp/lanes",
  },
  {
    key: "endpoint",
    label: "Endpoint",
    caption: "SMTP relays and delivery endpoints",
    href: "/smtp/endpoints",
  },
];

export const generalStats = [
  {
    label: "Queued Today",
    value: "18,240",
    meta: "+12.4%",
    tone: "bg-brand-500 text-white",
  },
  {
    label: "Delivered",
    value: "17,891",
    meta: "98.1%",
    tone: "bg-success-500 text-white",
  },
  {
    label: "Avg Send Latency",
    value: "1.8s",
    meta: "-240ms",
    tone: "bg-gray-900 text-white",
  },
  {
    label: "Template Coverage",
    value: "14",
    meta: "6 transactional",
    tone: "bg-warning-500 text-white",
  },
];

export const consumers: ConsumerItem[] = [
  {
    id: "smtp_consumer_redis_stream",
    name: "Redis Stream",
    stream: "smtp.outbound",
    status: "Active",
    detail: "Primary consumer for transactional mail fan-out.",
  },
  {
    id: "smtp_consumer_rabbitmq_bridge",
    name: "RabbitMQ Bridge",
    stream: "smtp.rabbitmq.bridge",
    status: "Planned",
    detail: "Reserved slot for high-volume campaign handoff.",
  },
  {
    id: "smtp_consumer_kafka_relay",
    name: "Kafka Relay",
    stream: "smtp.kafka.events",
    status: "Standby",
    detail: "Future event ingestion lane for multi-service publishing.",
  },
];

export const templates: TemplateItem[] = [
  {
    id: "smtp_template_verify_email",
    name: "Verify Email",
    category: "IAM",
    trafficClass: "critical_auth",
    subject: "Verify your Aurora email address",
    from: "Aurora Identity <identity@aurora.local>",
    to: "{{email}}",
    status: "Live",
    variables: ["full_name", "verification_link", "support_email"],
    consumer: "Redis Stream",
    body: "Hi {{full_name}},\n\nUse the verification link below to confirm your Aurora email address:\n{{verification_link}}\n\nIf you need help, contact {{support_email}}.",
  },
  {
    id: "smtp_template_forgot_password",
    name: "Forgot Password",
    category: "IAM",
    trafficClass: "critical_auth",
    subject: "Reset your Aurora password",
    from: "Aurora Security <security@aurora.local>",
    to: "{{email}}",
    status: "Live",
    variables: ["full_name", "reset_link", "requested_at"],
    consumer: "Redis Stream",
    body: "Hi {{full_name}},\n\nWe received a password reset request at {{requested_at}}.\nUse the reset link below to continue:\n{{reset_link}}",
  },
  {
    id: "smtp_template_welcome_operator",
    name: "Welcome Operator",
    category: "Lifecycle",
    trafficClass: "transactional",
    subject: "Your Aurora workspace is ready",
    from: "Aurora Platform <platform@aurora.local>",
    to: "{{email}}",
    status: "Draft",
    variables: ["full_name", "workspace_name", "getting_started_link"],
    consumer: "RabbitMQ Bridge",
    body: "Hi {{full_name}},\n\nYour workspace {{workspace_name}} is ready.\nStart here: {{getting_started_link}}",
  },
  {
    id: "smtp_template_delivery_alert",
    name: "Delivery Alert",
    category: "System",
    trafficClass: "transactional",
    subject: "SMTP delivery warning detected",
    from: "Aurora MailOps <mailops@aurora.local>",
    to: "ops@aurora.local",
    status: "Review",
    variables: ["endpoint_name", "error_rate", "dashboard_link"],
    consumer: "Kafka Relay",
    body: "Alert: delivery warning detected on {{endpoint_name}}.\nCurrent error rate: {{error_rate}}.\nOpen dashboard: {{dashboard_link}}",
  },
];

export const laneRoutes: LaneRoute[] = [
  {
    templateName: "Verify Email",
    endpointName: "Postmark Primary",
    routeType: "primary",
    priority: 100,
    status: "active",
  },
  {
    templateName: "Verify Email",
    endpointName: "SES Backup",
    routeType: "fallback",
    priority: 80,
    status: "standby",
  },
  {
    templateName: "Forgot Password",
    endpointName: "Postmark Primary",
    routeType: "primary",
    priority: 95,
    status: "active",
  },
  {
    templateName: "Welcome Operator",
    endpointName: "Mailgun Operations",
    routeType: "controlled",
    priority: 60,
    status: "planned",
  },
  {
    templateName: "Delivery Alert",
    endpointName: "Mailgun Operations",
    routeType: "primary",
    priority: 80,
    status: "standby",
  },
];

export const smtpEndpoints: DeliveryEndpoint[] = [
  {
    id: "smtp_postmark_primary",
    name: "Postmark Primary",
    host: "smtp.postmarkapp.com",
    port: 587,
    username: "aurora-primary",
    priority: 100,
    weight: 1,
    tlsMode: "starttls",
    status: "active",
    provider: "Postmark",
    note: "Primary path for IAM and transactional identity mail.",
  },
  {
    id: "smtp_ses_backup",
    name: "SES Backup",
    host: "email-smtp.ap-southeast-1.amazonaws.com",
    port: 465,
    username: "aurora-backup",
    priority: 80,
    weight: 1,
    tlsMode: "tls",
    status: "standby",
    provider: "Amazon SES",
    note: "Warm standby relay for password recovery and security notifications.",
  },
  {
    id: "smtp_mailgun_ops",
    name: "Mailgun Operations",
    host: "smtp.mailgun.org",
    port: 587,
    username: "ops-relay",
    priority: 60,
    weight: 1,
    tlsMode: "tls",
    status: "maintenance",
    provider: "Mailgun",
    note: "Reserved for system alert traffic during provider isolation tests.",
  },
];
